[dependencies]
anyhow = "1.0"
itertools = "0.10"
petgraph = "0.6"
regex = "1.7"
serde_json = "1.0"
serde_yaml = "0.9"

[dependencies.serde]
features = ["derive"]
version = "1.0"

[package]
edition = "2021"
name = "day-07"
version = "0.1.0"
